"""add_column_group_products

Revision ID: cd7d2305fff9
Revises: a9f0a6212b24
Create Date: 2026-04-24 09:33:25.750187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7d2305fff9'
down_revision: Union[str, Sequence[str], None] = 'a9f0a6212b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('group', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'group')
    # ### end Alembic commands ###
